-- MySQL Script generated by MySQL Workbench
-- Wed Sep 20 12:53:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cleanBlog_2017
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cleanBlog_2017
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cleanBlog_2017` DEFAULT CHARACTER SET utf8 ;
USE `cleanBlog_2017` ;

-- -----------------------------------------------------
-- Table `cleanBlog_2017`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanBlog_2017`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `pwd` VARCHAR(45) NOT NULL,
  `statut` INT NOT NULL DEFAULT 1,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanBlog_2017`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanBlog_2017`.`posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `sousTitre` VARCHAR(255) NULL,
  `datePublication` DATE NOT NULL,
  `texte` TEXT NULL,
  `user` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users_idx` (`user` ASC),
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`user`)
    REFERENCES `cleanBlog_2017`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanBlog_2017`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanBlog_2017`.`pages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `sousTitre` VARCHAR(45) NULL,
  `texte` VARCHAR(45) NULL,
  `titreMenu` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  `tri` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
